name: CI Gradle

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew pullAllPluginsSource check javadoc

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt install -y git
            sudo apt install -y openjdk-11-jdk
            sudo apt install -y gradle
            cat /etc/os-release
            sudo rm -rf ofbiz-pipeline
            git clone https://github.com/mnogueiraops/ofbiz-pipeline.git
            cd ofbiz-pipeline/gradle/
            ./init-gradle-wrapper.sh
